floods:
  global_flood_maps_url: https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/CEMS-GLOFAS/flood_hazard
  no_ensemble_members: 51
  minimum_flood_depth: 0.1
  glofas_threshold_url: https://confluence.ecmwf.int/display/CEMS/Auxiliary+Data
  glofas_threshold_files: flood_threshold_glofas_v4_rl
auxiliary:
  worldpop_url: https://data.worldpop.org/GIS/Population/Global_2021_2022_1km_UNadj/constrained/2022
databases:
  blob_container: ibfdatapipelines
  blob_storage_path: river-flood
  postgresql_server: 510-postgresql-flex-server.postgres.database.azure.com
  postgresql_port: 5432
  postgresql_database: global510
countries:
- name: DZA
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: AGO
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: BEN
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: BWA
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: BFA
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: BDI
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: CPV
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: CMR
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: CAF
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: TCD
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: COM
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: COD
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: COG
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: CIV
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: DJI
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: EGY
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: GNQ
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: ERI
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: SWZ
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: GAB
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: GMB
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: GHA
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: GIN
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: GNB
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: LSO
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: LBR
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: LBY
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: MDG
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: MLI
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: MRT
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: MUS
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: MAR
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: MOZ
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: NAM
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: NER
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: NGA
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: RWA
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: STP
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: SEN
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: SYC
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: SLE
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: SOM
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: ZAF
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: SDN
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: TZA
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: TGO
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: TUN
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
- name: ZWE
  admin-levels:
  - 1
  - 2
  - 3
  trigger-on-lead-time: 5
  trigger-on-return-period: 5
  trigger-on-minimum-probability: 0.75
  classify-alert-on: return-period
  alert-on-return-period:
    min: 1.5
    med: 2
    max: 5
  alert-on-minimum-probability: 0.6
